name: esv_bible
description: A future-based dart package for the ESV API from Crossway which can be used to fetch ESV bible passages.
version: 1.1.4
homepage: https://github.com/arielmagbanua/esv_bible

environment:
  sdk: ">=2.17.0 < 4.0.0"

dependencies:
  http: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.6
  mocktail: ^1.0.0
  lint: ^2.1.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
