name: esv_bible
description: A future-based dart package for the ESV API from Crossway which can be used to fetch ESV bible passages.
version: 1.1.2
homepage: https://github.com/arielmagbanua/esv_bible

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  test: ^1.21.4
  mocktail: ^0.3.0
  lint: ^1.10.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
